# tasks to install a grav site
- name: create temp folder
  file:
    path="{{ grav_temp_path }}/unpacked"
    state=directory
  become: yes

- name: download grav
  get_url:
  args:
    url: "{{ grav_url }}"
    dest: "{{ grav_temp_path }}/grav.zip"
  become: yes

- name: install unzip
  install:
  args:
    packages: "unzip"
  become: true

- name: unzip grav download
  unarchive:
  args:
    src: "{{ grav_temp_path }}/grav.zip"
    dest: "{{ grav_temp_path }}/unpacked"
    owner: "{{ grav_owner | default(omit) }}"
    group: "{{ grav_group | default(omit) }}"
    remote_src: yes
  become: true

- name: move site dir in place
  command: "mv {{ grav_temp_path }}/unpacked/grav {{ grav_site_dir }}"
  become: true

#TODO: group name for other distributions?
- name: chgroup for site dir
  file:
    path: "{{ grav_site_dir }}"
    owner: "{{ grav_webserver_user }}"
    group: "{{ grav_webserver_group }}"
    recurse: yes
  become: yes

- name: copy nginx.conf
  copy:
  args:
    src: "{{ grav_site_dir }}/webserver-configs/nginx.conf"
    force: no
    group: root
    owner: root
    remote_src: yes
    dest: "/etc/nginx/sites-available/{{ grav_site_name }}"
  become: true

- name: link grav site to sites-enabled
  file:
  args:
    dest: "/etc/nginx/sites-enabled/{{ grav_site_name }}"
    src: "/etc/nginx/sites-available/{{ grav_site_name }}"
    state: link
  become: true

- name: set web root
  lineinfile:
  args:
    path: "/etc/nginx/sites-available/{{ grav_site_name }}"
    line: "    root {{ grav_site_dir }};"
    regexp: '^\s*root.*;$'
  become: true

- name: remove php-fpm socket config
  lineinfile:
  args:
    path: "/etc/nginx/sites-available/{{ grav_site_name }}"
    state: absent
    regexp: "fastcgi_pass unix:"
  become: true

- name: set php-fpm pass config
  lineinfile:
  args:
    path: "/etc/nginx/sites-available/{{ grav_site_name }}"
    line: "        fastcgi_pass 127.0.0.1:9000;"
    regexp: "fastcgi_pass 127.0.0.1:9000;"
  become: true

- name: set listen port
  lineinfile:
  args:
    path: "/etc/nginx/sites-available/{{ grav_site_name }}"
    line: "    listen {{ grav_webserver_port }};"
    regexp: "listen.*;$"
  become: true

- name: remove user dir
  file:
  args:
    path: "{{ grav_site_dir }}/user"
    state: absent
  become: true

- name: link user dir
  file:
  args:
    src: "{{ grav_user_dir_expanded }}"
    dest: "{{ grav_site_dir }}/user"
    state: link
  become: true

- name: refresh gpm index for site
  command: bin/gpm  selfupgrade -f
  args:
    chdir: "{{ grav_site_dir }}"
  become_user: "{{ grav_webserver_user }}"
  become: yes
